# Generated by Django 3.2.16 on 2022-11-01 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_patient_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='emergency_phone_number',
            field=models.CharField(default='+7', max_length=12, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
