# Generated by Django 3.2.16 on 2022-11-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_patient_emergency_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
