# Generated by Django 4.1 on 2022-11-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_patient_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile_photo',
            field=models.ImageField(default='image.profile.png', null=True, upload_to=''),
        ),
    ]
