# Generated by Django 4.1 on 2022-12-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_contact_number_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_photo',
            field=models.ImageField(default='image.profile.png', null=True, upload_to='images/'),
        ),
    ]
